config/routes.rb
Rails.application.routes.draw do

  get 'react_examples/component', to: 'react_examples#component', as: :component
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: [:create, :destroy]
  resource :site, only: [:show]

  resources :clubs
  resources :users
  resources :kits
  resources :items
  resources :react # CHANGED <-- added this line.

  resources :conversations do
    resources :messages
  end

  root 'site#index'
end

app/models/message.rb
class Message < ApplicationRecord

  belongs_to :conversation
  belongs_to :user
  validates_presence_of :body, :conversation_id, :user_id

  def message_time
    created_at.strftime("%m/%d/%y at %l:%M %p")
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  before_action do
    @conversation = Conversation.find(params[:conversation_id])
  end

  def index
    @messages = @conversation.messages
    if @messages.length > 10
      @over_ten = true
      @messages = @messages[-10..-1]
    end
    if params[:m]
      @over_ten = false
      @messages = @conversation.messages
    end
    if @messages.last
      if @messages.last.user_id != current_user.id
        @messages.last.read = true;
      end
    end
    @message = @conversation.messages.new
  end

  def new
    @message = @conversation.messages.new
  end

  def create
    @message = @conversation.messages.new(message_params)
    if @message.save
      redirect_to conversation_messages_path(@conversation)
    end
  end

  private
  def message_params
    params.require(:message).permit(:body, :user_id)
  end
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/index.html.erb
<section class='conversation-section'>
  <div class="conversation-wrapper">
    <% if @over_ten %>
    <p>
      <%= link_to 'Show Previous', '?m=all' %>
    </p>
    <% end %>
    <div>
     <% @messages.each do |message| %>
      <% if message.body %>
       <% user = User.find(message.user_id) %>
       <div>
        <div class="content">
         <div class="header"><strong><%= user.name %></strong>
           <%= message.message_time %></div>
          <div class="list">
           <p>
            <i class="right triangle icon"></i>
             <%= message.body %>
          </p>
        </div>
       </div>
     </div>
     <% end %>
    <% end %>
    </div>
    <%= form_for [@conversation, @message], html: {class: "ui reply form"} do |f| %>
     <div class="field">
       <%= f.text_area :body, class: "form-control" %>
     </div>
     <%= f.text_field :user_id, value: current_user.id, type: "hidden" %>
     <div>
       <%= f.submit "Add Reply" %>
     </div>
    <% end %>
    <p>
      <%= link_to 'All Messages', conversations_url %>
    </p>
  </div>
</section>