config/routes.rb
Rails.application.routes.draw do

  get 'react_examples/component', to: 'react_examples#component', as: :component
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'

  resources :sessions, only: [:create, :destroy]
  resource :site, only: [:show]

  resources :clubs
  resources :users
  resources :kits
  resources :items
  resources :react # CHANGED <-- added this line.

  resources :conversations do
    resources :messages
  end

  root 'site#index'
end

app/models/conversation.rb
class Conversation < ApplicationRecord

  belongs_to :sender, :foreign_key => :sender_id, class_name: 'User'
  belongs_to :recipient, :foreign_key => :recipient_id, class_name: 'User'
  has_many :messages, dependent: :destroy
  validates_uniqueness_of :sender_id, :scope => :recipient_id

  scope :between, -> (sender_id,recipient_id) do
   where("(conversations.sender_id = ? AND conversations.recipient_id = ?)
   OR (conversations.sender_id = ? AND conversations.recipient_id =?)",
   sender_id,recipient_id, recipient_id, sender_id)
  end

end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController

  before_action :authenticate_with_http_digest

  def index
    @users = User.all
    @conversations = Conversation.all
  end

  def create
    if Conversation.between(params[:sender_id],params[:recipient_id]).present?
      @conversation = Conversation.between(params[:sender_id], params[:recipient_id]).first
    else
      @conversation = Conversation.create!(conversation_params)
    end

  redirect_to conversation_messages_path(@conversation)
  end

  private
    def conversation_params
      params.permit(:sender_id, :recipient_id)
    end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/index.html.erb
<section class='conversation-section'>
  <div class='conversation-wrapper'>
    <h1>Mailbox</h1>
   <ul>
     <% @conversations.each do |conversation| %>
     <% if conversation.sender_id == current_user.id || conversation.recipient_id == current_user.id %>
      <% if conversation.sender_id == current_user.id %>
      <div>
        <% recipient = User.find(conversation.recipient_id) %>
      </div>
      <% else %>
      <div>
        <% recipient = User.find(conversation.sender_id) %>
      </div>
      <% end %>
      <p>
        </li>
      <%= link_to recipient.name, conversation_messages_path(conversation)%>
        </li>
      </p>

     <% end %>
    <% end %>
  </ul>
 </div>
</section>

app/views/conversations/users.html.erb
<div class="ui segment">
 <h3>All Users</h3>
  <div class="ui list">
   <% @users.each do |user| %>
    <% if current_user != nil && user.id != current_user.id %>
     <div class="item">
   <%= user.name %> <%= link_to 'Send message', conversations_path(sender_id: current_user.id, recipient_id: user.id), method: 'post'%>
 </div>
  <% end %>
 <% end %>
 </div>
</div>